---
apiVersion: v1
kind: Service
metadata:
  name: rtail-udp
  labels:
    app: rtail
spec:
  ports:
  - name: ucp-9999
    port: 9999
    targetPort: 9999
    protocol: UDP
  selector:
    app: rtail
  type: ClusterIP
