---
apiVersion: v1
kind: Service
metadata:
  name: rtail-web
  labels:
    app: rtail
spec:
  ports:
  - name: tcp-8888
    port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: rtail
  type: LoadBalancer
